#!/usr/bin/env ruby
# Connect to VPN
#

require 'rubygems'
require 'rotp'
require 'pty'
require 'expect'
require 'optparse'
require 'pry'

config = {
	:my_secret => 'SECRET',
	:my_key => 'KEY',
	:my_username => 'USERNAME',
}

opts = {}
optparse = OptionParser.new do |opt|
	opt.banner = "Usage: runvpn zoneName"
	opt.on '-z ZONES', '--zone ZONES', Array, "Name of the zone you wish to connect to" do |z|
		opts[:zones] = z
	end
end
optparse.parse!

# Get One Time Password
totp = ROTP::TOTP.new config[:my_secret]
pass = config[:my_key] + totp.now

# Connect to VPN
opts[:zones].each do |zone|
  PTY.spawn "sudo service openvpn restart #{zone}" do |r_f,w_f|
	  r_f.expect "Enter Auth Username:" do
    	w_f.puts "#{config[:my_username]}\n"
	  end
  	r_f.expect "Enter Auth Password:" do
      w_f.puts "#{pass}\n"
  	end
  end
	sleep 30
end
