#!/bin/bash
#set -x
#########################
# Added functionality to automatically start/restart
# the VPNs without having to manually interfer.
# 
# ==============
# PREREQUISITES:
# ==============
# - Python
# - The authtoken script
# - This requires you to "sudo pip install onetimepass" to make authtoken work
# - Your OAUTH secret for the authtoken script
# - The variables below edited to match your personal use case.
# - The case statement below edited for your personal preference for vpn names
# - Finally, you need your vpn configs to be edited to have
#     auth-user-pass login.conf   
#   Normally they only have auth-user-pass.  Adding the login.conf part makes this work.
#
#########################
BASEFILE=~/.ssh/baseline
CONFFILE=~/.ssh/login.conf
SYMLINK=/etc/openvpn/login.conf

sudo uptime
sudo service openvpn status

case "$1" in
or)
  VPN="or"
  ;;
va)
  VPN="va"
  ;;
*)
  VPN="or va"
  ;;
esac

echo $VPN
for file in $VPN
do
AUTHTOKEN=`~/scripts/get_token`
  sed "a\
Welcom365${AUTHTOKEN}" $BASEFILE > $CONFFILE 
  sudo ln -sf $CONFFILE $SYMLINK
  sudo service openvpn restart $file
  rm $CONFFILE
  sudo rm $SYMLINK
done
sleep 5
service openvpn status
